// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mount_azure_blob.proto

package mount_azure_blob

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MountAzureBlobRequest struct {
	TargetPath           string   `protobuf:"bytes,1,opt,name=targetPath,proto3" json:"targetPath,omitempty"`
	AccountName          string   `protobuf:"bytes,2,opt,name=accountName,proto3" json:"accountName,omitempty"`
	ContainerName        string   `protobuf:"bytes,3,opt,name=containerName,proto3" json:"containerName,omitempty"`
	AccountKey           string   `protobuf:"bytes,4,opt,name=accountKey,proto3" json:"accountKey,omitempty"`
	TmpPath              string   `protobuf:"bytes,5,opt,name=tmpPath,proto3" json:"tmpPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MountAzureBlobRequest) Reset()         { *m = MountAzureBlobRequest{} }
func (m *MountAzureBlobRequest) String() string { return proto.CompactTextString(m) }
func (*MountAzureBlobRequest) ProtoMessage()    {}
func (*MountAzureBlobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_415cfe8908c67a8c, []int{0}
}

func (m *MountAzureBlobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountAzureBlobRequest.Unmarshal(m, b)
}
func (m *MountAzureBlobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountAzureBlobRequest.Marshal(b, m, deterministic)
}
func (m *MountAzureBlobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountAzureBlobRequest.Merge(m, src)
}
func (m *MountAzureBlobRequest) XXX_Size() int {
	return xxx_messageInfo_MountAzureBlobRequest.Size(m)
}
func (m *MountAzureBlobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MountAzureBlobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MountAzureBlobRequest proto.InternalMessageInfo

func (m *MountAzureBlobRequest) GetTargetPath() string {
	if m != nil {
		return m.TargetPath
	}
	return ""
}

func (m *MountAzureBlobRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *MountAzureBlobRequest) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *MountAzureBlobRequest) GetAccountKey() string {
	if m != nil {
		return m.AccountKey
	}
	return ""
}

func (m *MountAzureBlobRequest) GetTmpPath() string {
	if m != nil {
		return m.TmpPath
	}
	return ""
}

type MountAzureBlobResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MountAzureBlobResponse) Reset()         { *m = MountAzureBlobResponse{} }
func (m *MountAzureBlobResponse) String() string { return proto.CompactTextString(m) }
func (*MountAzureBlobResponse) ProtoMessage()    {}
func (*MountAzureBlobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_415cfe8908c67a8c, []int{1}
}

func (m *MountAzureBlobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MountAzureBlobResponse.Unmarshal(m, b)
}
func (m *MountAzureBlobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MountAzureBlobResponse.Marshal(b, m, deterministic)
}
func (m *MountAzureBlobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MountAzureBlobResponse.Merge(m, src)
}
func (m *MountAzureBlobResponse) XXX_Size() int {
	return xxx_messageInfo_MountAzureBlobResponse.Size(m)
}
func (m *MountAzureBlobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MountAzureBlobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MountAzureBlobResponse proto.InternalMessageInfo

func (m *MountAzureBlobResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*MountAzureBlobRequest)(nil), "MountAzureBlobRequest")
	proto.RegisterType((*MountAzureBlobResponse)(nil), "MountAzureBlobResponse")
}

func init() {
	proto.RegisterFile("mount_azure_blob.proto", fileDescriptor_415cfe8908c67a8c)
}

var fileDescriptor_415cfe8908c67a8c = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0xcb, 0xcd, 0x2f, 0xcd,
	0x2b, 0x89, 0x4f, 0xac, 0x2a, 0x2d, 0x4a, 0x8d, 0x4f, 0xca, 0xc9, 0x4f, 0xd2, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x57, 0xda, 0xc9, 0xc8, 0x25, 0xea, 0x0b, 0x92, 0x72, 0x04, 0xc9, 0x38, 0x01, 0x25,
	0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xe4, 0xb8, 0xb8, 0x4a, 0x12, 0x8b, 0xd2, 0x53,
	0x4b, 0x02, 0x12, 0x4b, 0x32, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x44, 0x84, 0x14,
	0xb8, 0xb8, 0x13, 0x93, 0x93, 0x41, 0x5a, 0xfd, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc0, 0x0a, 0x90,
	0x85, 0x84, 0x54, 0xb8, 0x78, 0x93, 0xf3, 0xf3, 0x4a, 0x12, 0x33, 0xf3, 0x52, 0x8b, 0xc0, 0x6a,
	0x98, 0xc1, 0x6a, 0x50, 0x05, 0x41, 0xf6, 0x40, 0x35, 0x79, 0xa7, 0x56, 0x4a, 0xb0, 0x40, 0xec,
	0x41, 0x88, 0x08, 0x49, 0x70, 0xb1, 0x97, 0xe4, 0x16, 0x80, 0x1d, 0xc1, 0x0a, 0x96, 0x84, 0x71,
	0x95, 0xb4, 0xb8, 0xc4, 0xd0, 0x9d, 0x5e, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc0, 0xc5,
	0x9c, 0x5a, 0x54, 0x04, 0x75, 0x34, 0x88, 0x69, 0x14, 0xcc, 0xc5, 0x03, 0x56, 0x1b, 0x9c, 0x5a,
	0x54, 0x96, 0x99, 0x9c, 0x2a, 0xe4, 0xcc, 0xc5, 0x87, 0xaa, 0x57, 0x48, 0x4c, 0x0f, 0x6b, 0x38,
	0x48, 0x89, 0xeb, 0x61, 0xb7, 0x44, 0x89, 0x21, 0x89, 0x0d, 0x1c, 0x86, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xf8, 0x06, 0xab, 0xca, 0x5d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MountServiceClient is the client API for MountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MountServiceClient interface {
	MountAzureBlob(ctx context.Context, in *MountAzureBlobRequest, opts ...grpc.CallOption) (*MountAzureBlobResponse, error)
}

type mountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMountServiceClient(cc grpc.ClientConnInterface) MountServiceClient {
	return &mountServiceClient{cc}
}

func (c *mountServiceClient) MountAzureBlob(ctx context.Context, in *MountAzureBlobRequest, opts ...grpc.CallOption) (*MountAzureBlobResponse, error) {
	out := new(MountAzureBlobResponse)
	err := c.cc.Invoke(ctx, "/MountService/MountAzureBlob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MountServiceServer is the server API for MountService service.
type MountServiceServer interface {
	MountAzureBlob(context.Context, *MountAzureBlobRequest) (*MountAzureBlobResponse, error)
}

// UnimplementedMountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMountServiceServer struct {
}

func (*UnimplementedMountServiceServer) MountAzureBlob(ctx context.Context, req *MountAzureBlobRequest) (*MountAzureBlobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MountAzureBlob not implemented")
}

func RegisterMountServiceServer(s *grpc.Server, srv MountServiceServer) {
	s.RegisterService(&_MountService_serviceDesc, srv)
}

func _MountService_MountAzureBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MountAzureBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MountServiceServer).MountAzureBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MountService/MountAzureBlob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MountServiceServer).MountAzureBlob(ctx, req.(*MountAzureBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MountService",
	HandlerType: (*MountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MountAzureBlob",
			Handler:    _MountService_MountAzureBlob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mount_azure_blob.proto",
}
